### ISSUE TITLE
Repo Request

### ISSUE THREAD

**Issue by abbasmashaddy72** [omranooo91/laravel-simple-blog#1]
Hi @omranooo91,
Your MultiLanguage Video is Great,

It will be great if you share the git repo of this project to get hands-on, as I don't know Arabic Language it being difficult for me to follow up with you on the video courses waiting for your reply.

I was not able to think how to get in contact with you so, I created an issue to your project to get connected with you, I am really sorry for that.

Thanks in Advance

**Comment by omranooo91** [comment]
Hello bro

I am glad that you are benefiting from my videos
I will be uploading the files for the project today

Thanks

**Comment by abbasmashaddy72** [comment]
Thanks Bro @omranooo91 

Can You Share the Link after Uploading or else can add me in the repo

abbasmashaddy72 is my GitHub ID

**Comment by omranooo91** [comment]
https://github.com/omranooo91/blog

**Comment by abbasmashaddy72** [comment]
Thank You Very Much Brother

**Comment by omranooo91** [comment]
you're welcome
